kv_namespaces = [
  { binding = "KV", id = "b686270fac8d49eaac70bb99df73fa6e", preview_id = "d3c77ad11ed149579af4faddd04da1e3" }
]

r2_buckets  = [
  { binding = "BUCKET", bucket_name = "patio", preview_bucket_name = "patio-dev" }
]
